#!/usr/bin/env python3
"""Compute the group generated by the logical symplectic matrices of a code's automorphisms.

First runs aut_logical_action to display the per-generator symplectic actions, then
enumerates the group generated by those matrices via BFS over GF(2) matrix products
and reports the group order, kernel size, and which generators act trivially.

Usage:
    python aut_logical_group.py <n> <k> <id>

Examples:
    python aut_logical_group.py 7 1 226      # Steane: expect |logical group| = 6 (S_3)
    python aut_logical_group.py 9 3 170235
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

import aut_logical_action as ala


# ── GF(2) matrix arithmetic ───────────────────────────────────────────────────

def mat_mul(A, B):
    """Multiply two square GF(2) matrices given as tuples of row-tuples."""
    d = len(A)
    return tuple(
        tuple(sum(A[r][i] * B[i][c] for i in range(d)) % 2 for c in range(d))
        for r in range(d)
    )


def identity(d):
    return tuple(tuple(int(i == j) for j in range(d)) for i in range(d))


# ── BFS group enumeration ─────────────────────────────────────────────────────

def bfs_group(gen_mats):
    """Return the set of all group elements reachable from the identity via gen_mats."""
    if not gen_mats:
        return {identity(len(gen_mats[0]))} if gen_mats else {()}
    d = len(gen_mats[0])
    I = identity(d)
    group = {I}
    frontier = {I}
    while frontier:
        nxt = set()
        for g in frontier:
            for m in gen_mats:
                p = mat_mul(g, m)
                if p not in group:
                    group.add(p)
                    nxt.add(p)
        frontier = nxt
    return group


# ── main ──────────────────────────────────────────────────────────────────────

def main():
    if len(sys.argv) != 4:
        print(__doc__)
        sys.exit(1)

    n, k, code_id = int(sys.argv[1]), int(sys.argv[2]), int(sys.argv[3])

    # ── Part 1: per-generator logical action ─────────────────────────────────
    # aut_logical_action.main() reads sys.argv directly, so args carry through.
    ala.main()

    # ── Part 2: BFS over the generated symplectic group ──────────────────────
    gen_mats, aut_size, info = ala.get_logical_matrices(n, k, code_id)

    I = identity(2 * k)
    trivial   = [info['generators'][i] for i, m in enumerate(gen_mats) if m == I]
    nontrivial = [info['generators'][i] for i, m in enumerate(gen_mats) if m != I]

    # Deduplicate generator matrices before BFS (preserves order)
    seen = set()
    distinct_mats = []
    for m in gen_mats:
        if m not in seen:
            seen.add(m)
            distinct_mats.append(m)

    group = bfs_group(distinct_mats)
    log_order = len(group)
    kernel_size = aut_size // log_order if aut_size else '?'

    sep = "=" * 55
    print(sep)
    print("Logical group  (BFS over GF(2) symplectic matrices)")
    print(sep)
    print(f"  Generator matrices (total)    : {len(gen_mats)}")
    print(f"  Generator matrices (distinct) : {len(distinct_mats)}")
    print(f"  Acting trivially (= identity) : {len(trivial)}")
    print(f"  Acting non-trivially          : {len(nontrivial)}")
    print()
    print(f"  |Aut(code)|      = {aut_size}")
    print(f"  |logical group|  = {log_order}")
    print(f"  |kernel|         = {kernel_size}")
    print()

    if trivial:
        print(f"  Trivial generators:")
        for g in trivial:
            print(f"    {g}")
        print()

    if nontrivial:
        print(f"  Non-trivial generators:")
        for g in nontrivial:
            print(f"    {g}")
        print()


if __name__ == "__main__":
    main()
