#!/usr/bin/env python3
"""Identify the GAP SmallGroup of a code's logical automorphism group.

Runs aut_logical_group to display per-generator logical actions and the BFS
group order, then builds a GAP matrix-group script, runs it, and prints the
group's order, IdSmallGroup (when the order is in the SmallGroups database),
and StructureDescription.

Usage:
    python aut_logical_gap.py <n> <k> <id> [gap_executable]

Examples:
    python aut_logical_gap.py 7 1 226          # Steane: expect S3
    python aut_logical_gap.py 9 3 170235       # [[9,3,3]]
"""

import subprocess
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

import aut_logical_action as ala
import aut_logical_group as alg

GAP_EXE_DEFAULT = "/home/valbert/gap-4.15.1/gap"

def _in_small_groups(order):
    """Return True if GAP's SmallGroups database covers this order."""
    return 1 <= order <= 2000 and order != 1024


def identity(d):
    return tuple(tuple(int(i == j) for j in range(d)) for i in range(d))


def mat_to_gap(M, varname):
    """Return a GAP assignment string for a GF(2) matrix."""
    rows = []
    for row in M:
        entries = ", ".join("One(GF(2))" if b else "Zero(GF(2))" for b in row)
        rows.append(f"  [{entries}]")
    body = ",\n".join(rows)
    return f"{varname} := [\n{body}\n]*One(GF(2));;"


def build_gap_script(gen_mats):
    """Return a GAP script that identifies the group generated by gen_mats."""
    lines = []
    for i, m in enumerate(gen_mats):
        lines.append(mat_to_gap(m, f"g{i + 1}"))
    gens_str = ", ".join(f"g{i + 1}" for i in range(len(gen_mats)))
    lines += [
        f"G := Group({gens_str});;",
        'ord := Order(G);;',
        'Print("|G| = ", ord, "\\n");;',
        "if ord <= 2000 and ord <> 1024 then",
        '  Print("IdSmallGroup = ", IdSmallGroup(G), "\\n");;',
        "fi;;",
        'Print("StructureDescription = ", StructureDescription(G), "\\n");;',
        "QUIT;;",
    ]
    return "\n".join(lines)


def run_gap(script, gap_exe):
    """Write script to a temp file, run GAP, return (stdout, stderr)."""
    with tempfile.NamedTemporaryFile(mode="w", suffix=".g", delete=False) as f:
        f.write(script)
        fname = f.name
    try:
        result = subprocess.run(
            [gap_exe, "-q", fname],
            stdin=subprocess.DEVNULL,
            capture_output=True, text=True, timeout=180,
        )
    finally:
        Path(fname).unlink(missing_ok=True)
    return result.stdout, result.stderr


def main():
    if len(sys.argv) not in (4, 5):
        print(__doc__)
        sys.exit(1)

    n, k, code_id = int(sys.argv[1]), int(sys.argv[2]), int(sys.argv[3])
    gap_exe = sys.argv[4] if len(sys.argv) == 5 else GAP_EXE_DEFAULT

    # ── Part 1: per-generator display + BFS summary ───────────────────────────
    # Trim argv so aut_logical_group.main() sees exactly the three positional args.
    saved_argv = sys.argv[:]
    sys.argv = sys.argv[:4]
    alg.main()
    sys.argv = saved_argv

    # ── Part 2: build distinct non-trivial generator matrix set ──────────────
    gen_mats, _aut_size, _info = ala.get_logical_matrices(n, k, code_id)
    I = identity(2 * k)
    seen = set()
    distinct_mats = []
    for m in gen_mats:
        if m not in seen:
            seen.add(m)
            if m != I:
                distinct_mats.append(m)

    sep = "=" * 55
    print(sep)
    print("GAP SmallGroup identification")
    print(sep)

    if not distinct_mats:
        print("  All generators act trivially — logical group is {e}.")
        print("  GAP: SmallGroup(1, 1)")
        print()
        return

    # ── Part 3: run GAP ───────────────────────────────────────────────────────
    script = build_gap_script(distinct_mats)
    stdout, stderr = run_gap(script, gap_exe)

    if stderr.strip():
        print("  GAP stderr:")
        for line in stderr.strip().splitlines():
            print(f"    {line}")
        print()

    for line in stdout.splitlines():
        print(f"  {line}")
    print()


if __name__ == "__main__":
    main()
